AttributeError: 'Drawing' object has no attribute 'add_line'
dwg is a Drawing object, to add lines you would need to create either a layout or a modelspace.