Duplicate variable name broke Cython compatibility
I was trying to get ezdxf to compile with Cython and was getting this error:

File "acdsdata.py", line 172, in ezdxf.sections.acdsdata.AcDsRecord.__init__
UnboundLocalError: local variable 'tags' referenced before assignment

I was able to get it to compile by changing the duplicate variable name tags to group.